- hosts: all
  tasks:
- name: Print a message
  ansible.builtin.debug:
    msg: "Always runs"
  tags:
  - always
  vars_prompt:
    - name: branch
      prompt: 'Enter a branch to deploy'
      default: test_branch
      private: no
