- name: installing packeges
  hosts: tower2
  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: present
    - name: starting httpd service
      service:
        name: httpd
        state: started
